### ISSUE TITLE
Feedback (/about-us) - resolve design feedback

### ISSUE THREAD

**Issue by activate-glacier-instinct** [BanklessDAO/bankless-website#19]
## Tasks
- [ ] Make the background black (#000000)
- [ ] background gradient, can be an SVG if CSS isnt doing justice
- [ ] (WANT ALPHA ?) was ommitted
- [ ] image & GIF cards have a bordr radius of 10px
- [ ] DAO flag is a GIF also, do let us know if you need to get this assets.
- [ ] Wrong video was used on the About Us page, do let us know for the video

## Design feedback doc

https://docs.google.com/document/d/16rgUYfjsiRM338j70WWRnDX3tj6UM7ZMs-B88NGwGyg/edit

**Comment by CompositeFellow** [comment]
- [ ] Mobile break points are broken. example look at 1000 width screen
- [ ] Subpages not responsive at lower screen sizes
- [ ] Title is not responsive to lower screen sizes
